### ISSUE TITLE
category `set` is broken

### ISSUE THREAD

**Issue by Darkilen** [dofapi/crawlit-dofus-encyclopedia-parser#12]
An error occurred when we try to parse `set` category.

![set_broken](https://user-images.githubusercontent.com/22028659/54549302-13627b80-49aa-11e9-9d11-043ca93e8669.png)

App crash here : [lib/item-crawler/getSets.js#L33](https://github.com/raczak/crawlit-dofus-encyclopedia-parser/blob/master/lib/item-crawler/getSets.js#L33)

**Comment by raczak** [comment]
Thanks for sharing, I'm working on it :+1:
