### ISSUE TITLE
Catch error when 404 received

### ISSUE THREAD

**Issue by Cobelt** [dofapi/crawlit-dofus-encyclopedia-parser#40]
Hello,
I tried your tool today on weapons (game: dofus, language: french) and it crashed on this item :
https://www.dofus.com/fr/mmorpg/encyclopedie/armes/14164-arc-honte (but it's visible in their encyclopedia list)

I think that could be better to do an array that say at the end of the run "Hey, we've got a 404 on those items : Arc Honte, ..." than to crash everything for one that doesn't exist ! :)

**Comment by raczak** [comment]
Thank you @Cobelt for raising this issue, it's fix now. In fact we were already checking 404 status of each item but with crawlit major update we forgot to adapt the logic.

fix in commit https://github.com/dofapi/crawlit-dofus-encyclopedia-parser/commit/4d5454c4c2422cf0d5f8555d662800e15b0a0d7e
