### ISSUE TITLE
% crit valeur fixe

### ISSUE THREAD

**Issue by Cobelt** [dofapi/crawlit-dofus-encyclopedia-parser#43]
Hello,
Another bug in crit. If an item have a fixed value of crit, it's not parsed correctly.
For example, the Spookkoth amulet which have 2% crit :
Should get :  "% Critique": { max (or min): "2" }; but actually got "2% Critique" : { min: "2", max: null }

That cause me some trouble because I use the stat name to get the icon associated.

PS: If I can get me some free time to learn how your crawler works and find the problem, I'll try to make a PR :)

**Comment by JulienCoutault** [comment]
Hi,

For me, it should get : `"% Critique": { min, "2", max: "2" }`

**Comment by Cobelt** [comment]
For AP it's "AP": { "min": "1", "max": null }, that's why it was my example but yeah I think you're right and it should be min and max to the same value !

**Comment by JulienCoutault** [comment]
By bad, i didn't know that.

**Comment by Cobelt** [comment]
Here is my PR : https://github.com/dofapi/crawlit-dofus-encyclopedia-parser/pull/44

**Comment by raczak** [comment]
fixed in #44
