### ISSUE TITLE
Error 500 when fetching every equipments

### ISSUE THREAD

**Issue by Cobelt** [dofapi/crawlit-dofus-encyclopedia-parser#45]
I don't know if it's from my modifications or if it's from dofus website but when fetching all equipments at once, I'm having a 500 error on https://www.dofus.com/fr/mmorpg/encyclopedie/equipements?size=3000 
(In browser it doesn't work for me neither) 

I'm not having the issue if size <= 252, so I think it will need some modifications as a loop with page counter and size = 252

**Comment by Paul-Marie** [comment]
Hello @Cobelt 

There is no problem anymore, I tried this morning and the crawler is again able to fetch all equipment, weapons, resources, etc ...
Enjoy !

**Comment by Cobelt** [comment]
Okay I though Dofus did this to block crawlers 
Thank you @Paul-Marie !

**Comment by Cobelt** [comment]
In fact https://www.dofus.com/fr/mmorpg/encyclopedie/equipements?size=3000 return only 96 items, so I need tp reopen the issue :/

**Comment by Paul-Marie** [comment]
Hmmm, that's true.

On the 2957 foundable equipements, only 96 are fetched. cuz dofapitouch seems to only give the first page, and only 96 items / pages are displayed by default (use the link can be easier to ya to understand)

**Comment by Cobelt** [comment]
Yeah I knew why it's doing that, I'm currently looking to make a loop and get all pages, I'll make a PR when it's working !

**Comment by Paul-Marie** [comment]
Feel free to join this discord: http://discord.dofapi.fr

And go tag every @Administrators x)

**Comment by raczak** [comment]
As @Paul-Marie said, don't hesitate to join the discord and discuss with us :smile:

**Comment by Cobelt** [comment]
Already joined @raczak :)

**Comment by raczak** [comment]
Issue fixed in "I forget which commit ! :p"
