### ISSUE TITLE
Works in 1.29?

### ISSUE THREAD

**Issue by Prozaks** [dofapi/crawlit-dofus-encyclopedia-parser#48]
Hello!
I am developing an encyclopedia for a University job.
I've been looking everywhere for images of resources and maps of version 1.29.
Do you think there is the possibility of obtaining them from here? I need the old versions.
Otherwise, do you know how or where can I get them?

**Comment by Aperrix** [comment]
Hi @Prozaks !

Glad to see that our tool can help you develop your school project 😃 
We are actively working to make Dofus 1.29's data available.

Stay connected ! 😉
